### PR TITLE
fix: if applied this commit will fix the build

### PR DESCRIPTION
**Pull request by helio-frota**
on xubuntu 18.04.

### CODE REVIEW

**Comment by helio-frota** [comment]
before:

```
marinara fix-build🔒 ✅  cargo build
   Compiling marinara v0.1.2-alpha.0 (file:///home/hf/Desktop/marinara)                                                                                                                                            
error: cannot find derive macro `StructOpt` in this scope
  --> src/main.rs:22:17
   |
22 | #[derive(Debug, StructOpt)]
   |                 ^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/main.rs:27:9
   |
27 |         #[structopt(short = "f", long = "force")]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/main.rs:25:5
   |
25 |     #[structopt(name = "init", about = "initialize configuration")]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/main.rs:31:5
   |
31 |     #[structopt(name = "start", about = "start a new pomodoro")]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/main.rs:33:5
   |
33 |     #[structopt(name = "stop", about = "stop current pomodoro")]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/main.rs:35:5
   |
35 |     #[structopt(name = "status", about = "current pomodoro status")]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/main.rs:23:1
   |
23 | #[structopt(name = "marinara", about = "pomodoro timer")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 7 previous errors
```

after: 

```
marinara fix-build🔒 ✅  cargo build
   Compiling marinara v0.1.2-alpha.0 (file:///home/hf/Desktop/marinara)                                                                                                                                            
    Finished dev [unoptimized + debuginfo] target(s) in 1.70s

marinara fix-build🔒 ✅  ./target/debug/marinara status
W: 16m
```

**Comment by helio-frota** [comment]
closing this PR. it was automatically solved after update rust version to 1.30x

:+1:

**Comment by qmx** [comment]
yea, this only works on latest rust stable :)
